root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/server"
  bin = "./tmp/api"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 200
  kill_delay = 500

[log]
  time = true
